### ISSUE TITLE
Template Validation Error if "functions:" section is not empty 

### ISSUE THREAD

**Issue by exoego** [temyers/serverless-localstack#22]
I am interested in this project for faster local development cycle & CI with serverless framework.

During expriment, I got stuck with error: `The CloudFormation template is invalid: Template Validation Error: 'NoneType' object has no attribute '__getitem__'` 
It seems that template validation fails if one or more function is defined in `functions: ` section of swagger.yml.

Note: To know the reason for errors, I have locally built serverless-locakstack with pull request https://github.com/temyers/serverless-localstack/pull/20, that enables template validation.

Any help is highly appreciated.

# Run successfully if `functions: ` is empty

Running localstack with 
```bash
$ docker run -it -p 4567-4582:4567-4582 -p 8180:8180 -e PORT_WEB_UI=8180 localstack/localstack:0.8.5
2018-03-03 07:26:04,510 CRIT Supervisor running as root (no user in config file)
2018-03-03 07:26:04,512 INFO supervisord started with pid 1
2018-03-03 07:26:05,515 INFO spawned: 'dashboard' with pid 9
2018-03-03 07:26:05,517 INFO spawned: 'infra' with pid 10
(. .venv/bin/activate; bin/localstack web)
(. .venv/bin/activate; exec bin/localstack start)
Starting local dev environment. CTRL-C to quit.
2018-03-03T07:26:06:INFO:werkzeug:  * Running on http://0.0.0.0:8180/ (Press CTRL+C to quit)
2018-03-03T07:26:06:INFO:werkzeug:  * Restarting with stat
Starting mock API Gateway (http port 4567)...
Starting mock DynamoDB (http port 4569)...
Starting mock SES (http port 4579)...
Starting mock Kinesis (http port 4568)...
Starting mock Redshift (http port 4577)...
Starting mock S3 (http port 4572)...
Starting mock CloudWatch (http port 4582)...
Starting mock CloudFormation (http port 4581)...
Starting mock SSM (http port 4583)...
Starting mock SQS (http port 4576)...
Starting local Elasticsearch (http port 4571)...
2018-03-03 07:26:06,697 INFO success: dashboard entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-03-03 07:26:06,697 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Starting mock SNS (http port 4575)...
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock Firehose service (http port 4573)...
Starting mock Route53 (http port 4580)...
2018-03-03T07:26:08:WARNING:werkzeug:  * Debugger is active!
2018-03-03T07:26:08:INFO:werkzeug:  * Debugger PIN: 128-246-970
2018-03-03T07:26:15:WARNING:infra.pyc: Service "elasticsearch" not yet available, retrying...
Starting mock ES service (http port 4578)...
Starting mock Lambda service (http port 4574)...
Ready.
```

swagger.yml

```yaml
service: "hello"
provider:
  name: "aws"
  stage: ${opt:stage}
functions: []
plugins:
  - "serverless-localstack"
package:
  artifact: "../../target/lambda.zip"
custom:
  localstack:
    debug: true
    endpoints:
      S3: http://localhost:4572
      DynamoDB: http://localhost:4570
      CloudFormation: http://localhost:4581
      Elasticsearch: http://localhost:4571
      ES: http://localhost:4578
      SNS: http://localhost:4575
      SQS: http://localhost:4576
      Lambda: http://localhost:4574
      Kinesis: http://localhost:4568
```

console

```bash
$ serverless deploy --stage local
Serverless: Packaging service...
Serverless: config.options_stage: local
Serverless: serverless.service.custom.stage: undefined
Serverless: serverless.service.provider.stage: local
Serverless: Using serverless-localstack-plugin
Serverless: Reconfiguring service S3 to use http://localhost:4572
Serverless: Reconfiguring service DynamoDB to use http://localhost:4570
Serverless: Reconfiguring service CloudFormation to use http://localhost:4581
Serverless: Reconfiguring service Elasticsearch to use http://localhost:4571
Serverless: Reconfiguring service ES to use http://localhost:4578
Serverless: Reconfiguring service SNS to use http://localhost:4575
Serverless: Reconfiguring service SQS to use http://localhost:4576
Serverless: Reconfiguring service Lambda to use http://localhost:4574
Serverless: Reconfiguring service Kinesis to use http://localhost:4568
Serverless: Service files not changed. Skipping deployment...
Service Information
service: hello
stage: local
region: us-east-1
stack: hello-local
api keys:
  None
endpoints:
  None
functions:
  None
```

# Error if function is defined in `functions:` section

```yaml
service: "hello"
provider:
  name: "aws"
  stage: ${opt:stage}
functions:
  helloWorld:
    handler: handler.helloWorld
    events:
      - http:
          path: hello
          method: get
plugins:
  - "serverless-localstack"
package:
  artifact: "../../target/lambda.zip"
custom:
  localstack:
    debug: true
    endpoints:
      S3: http://localhost:4572
      DynamoDB: http://localhost:4570
      CloudFormation: http://localhost:4581
      Elasticsearch: http://localhost:4571
      ES: http://localhost:4578
      SNS: http://localhost:4575
      SQS: http://localhost:4576
      Lambda: http://localhost:4574
      Kinesis: http://localhost:4568
```

Console.

```bash
> serverless deploy --env dev --stage local
Serverless: Packaging service...
Serverless: config.options_stage: local
Serverless: serverless.service.custom.stage: local
Serverless: serverless.service.provider.stage: local
Serverless: Using serverless-localstack-plugin
Serverless: Reconfiguring service apigateway to use http://localhost:4567
Serverless: Reconfiguring service cloudformation to use http://localhost:4581
Serverless: Reconfiguring service cloudwatch to use http://localhost:4582
Serverless: Reconfiguring service lambda to use http://localhost:4574
Serverless: Reconfiguring service dynamodb to use http://localhost:4567
Serverless: Reconfiguring service s3 to use http://localhost:4572
Serverless: Reconfiguring service ses to use http://localhost:4579
Serverless: Reconfiguring service sns to use http://localhost:4575
Serverless: Reconfiguring service sqs to use http://localhost:4576
Serverless: Reconfiguring service CloudFormation to use http://localhost:4581
Serverless: Reconfiguring service Lambda to use http://localhost:4574
Serverless: Reconfiguring service ES to use http://localhost:4578
Serverless: Reconfiguring service DynamoDBStreams to use http://localhost:4570
Serverless: Reconfiguring service CloudWatch to use http://localhost:4582
Serverless: Reconfiguring service DynamoDB to use http://localhost:4569
Serverless: Reconfiguring service SES to use http://localhost:4579
Serverless: Reconfiguring service S3 to use http://localhost:4572
Serverless: Reconfiguring service SNS to use http://localhost:4575
Serverless: Reconfiguring service APIGateway to use http://localhost:4567
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Validating template...
 
  Error --------------------------------------------------
 
  The CloudFormation template is invalid: Template Validation Error: 'NoneType' object has no attribute '__getitem__'
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.9.4
     Serverless Version:     1.26.1
```
