### ISSUE TITLE
Redundant host names in the configuration

### ISSUE THREAD

**Issue by yohei1126** [temyers/serverless-localstack#8]
Host name is specified on all endpoints. I feel this is redundant. Is there any use case that we want to specify different endpoint for each service? 

```
custom:
  localstack:
    host: http://localhost
    endpoints:
      S3: http://localhost:4572
      DynamoDB: http://localhost:4570
      CloudFormation: http://localhost:4581
      Elasticsearch: http://localhost:4571
      ES: http://localhost:4578
      SNS: http://localhost:4575
      SQS: http://localhost:4576
      Lambda: http://localhost:4574
      Kinesis: http://localhost:4568
```

If not, we should specify host name once, then specify port on each services.

```
custom:
  localstack:
    host: http://localhost
    ports:
      S3: 4572
      DynamoDB: 4570
      CloudFormation: 4581
      Elasticsearch: 4571
      ES: 4578
      SNS: 4575
      SQS: 4576
      Lambda: 4574
      Kinesis: 4568
```

**Comment by yohei1126** [comment]
OK, I understand.

We can specify host only.

```
custom:
    localstack:
      host: http://localhost
```

Or we can specify specific endpoints.

```
custom:
  localstack:
    endpoints:
      S3: http://localhost:4572
      Kinesis: 4568
```

It this correct?
